/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SimpleProgressbar {
        /**
          * The value for progress indicator
         */
        "value": number;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSimpleProgressbarElement extends Components.SimpleProgressbar, HTMLStencilElement {
    }
    var HTMLSimpleProgressbarElement: {
        prototype: HTMLSimpleProgressbarElement;
        new (): HTMLSimpleProgressbarElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "simple-progressbar": HTMLSimpleProgressbarElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SimpleProgressbar {
        /**
          * An event that is passed to parent component by emitting updated value
         */
        "onStatusUpdate"?: (event: CustomEvent<any>) => void;
        /**
          * The value for progress indicator
         */
        "value"?: number;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "simple-progressbar": SimpleProgressbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "simple-progressbar": LocalJSX.SimpleProgressbar & JSXBase.HTMLAttributes<HTMLSimpleProgressbarElement>;
        }
    }
}
